jekyll/jekyll-sass-converter

jekyll-sass-converter.gemspec

This will update the version of Sass to be the most recent (per the conversation at https://github.com/jekyll/jekyll/issues/3973). It should at least allow for #12 to be possible (source maps enabled in 3.3).
As a note: I did some local tests to ensure generation could occur— but am not sure the best way to run tests outside of that. Also will need to bump the version number for deploy.

Update the version of Sass to be 3.4.x

---

lib/jekyll/converters/scss.rb
spec/sass_converter_spec.rb
spec/scss_converter_spec.rb

Sass optimizes compressed CSS output by adding a Byte Order Mark when the CSS contains non-ASCII characters. In Jekyll's use case, this can result in a BOM ending up in the middle of a generated HTML file when the `scssify`/`sassify` filters are used. The result is unparseable CSS.
The solution is to remove the Byte Order Mark and replace it with the equivalent `@charset "UTF-8";` rule.
In some cases, such as in highlighted snippets, it may be undesirable for the charset rule to be injected. Thus, a default-to-true configuration option `add_charset` is included allowing Jekyll users to disable this if desired.
This is a migration of Jekyll [#3914](https://github.com/jekyll/jekyll/issues/3914) and its associated [PR #3934](https://github.com/jekyll/jekyll/pull/3934), CC: @envygeeks, …

Strip byte order mark from generated compressed Sass/SCSS

---

lib/jekyll/converters/scss.rb
spec/sass_converter_spec.rb
spec/scss_converter_spec.rb

Ref #39
`add_charset` is now set to `false` by default.

add_charset false by default, but still strip BOM

---

.travis.yml

Jekyll 2.5 triggers a problem with Ruby 2.3's handling of singleton classes.

Don't test Jekyll 2.5 against Ruby 2.3.

---

lib/jekyll/converters/scss.rb
spec/scss_converter_spec.rb

`load_paths` is currently only supported in safe mode. This enables it all the time, but sanitizes the paths with `Jekyll.sanitized_path` in safe mode to ensure all paths are relative to the source directory. This also adds support for globbing (e.g. `**/*/node_modules` to add node modules and all transient dependencies to the load path).
Having multiple paths in the sass load path is really helpful when using package managers like bower or NPM. For example:
``` yaml
sass:
load_paths:
- bower_components
- **/*/node_modules
```
The motivation for this change is so I can use the latest version of [primer](https://github.com/primer/primer) on a jekyll site.
/cc @jonrohan

Allow load_paths in safe mode with sanitization

---

lib/jekyll/converters/scss.rb

Addresses a potential issue from #50.
/cc @jekyll/gh-pages

SCSS converter: expand @config["source"] to be "safer".

---

.rubocop.yml
Gemfile
Rakefile
jekyll-sass-converter.gemspec
lib/jekyll-sass-converter.rb
lib/jekyll-sass-converter/version.rb
lib/jekyll/converters/sass.rb
lib/jekyll/converters/scss.rb
spec/sass_converter_spec.rb
spec/scss_converter_spec.rb
spec/spec_helper.rb

This PR is the result of adding `inherit_gem:\n jekyll: .rubocop.yml` to `.rubocop.yml` and running `rubocop -a` so that this project follows Jekyll core's coding styles for consistency like other core plugins. This way, as Jekyll's Ruby style changes, so too will this project's.

Inherit Jekyll's rubocop config for consistency

---

lib/jekyll/converters/sass.rb
lib/jekyll/converters/scss.rb

A converter's `#matches` is one of the frequently called methods from `Jekyll::Renderer` (for every page / document)
This change eliminates repeated initializations of regexes not dependent on converter instance

Cache stateless regexes in class constants

---

lib/jekyll/converters/scss.rb

SassC includes line number and filename of sass partial in the exception message
Output from older `Sass` with a sample Jekyll site:
```
Invalid CSS after " color": expected ";", was ": #ddd;" on line 15
```
The same output when using this branch:
```
Error: Invalid CSS after " color": expected "}", was ": #ddd;" on line 15 of _sass/_style.scss
from line 8 of stdin >> color: #ddd; --^
```

SyntaxError line and filename are set by SassC

---

lib/jekyll/converters/scss.rb
spec/sass_converter_spec.rb
spec/scss_converter_spec.rb
spec/spec_helper.rb

Add `_sass` from within theme-gems to `Sass.load_paths` if the current site uses a theme gem and the theme-gem contains `_sass` directory at its root.

Configure Sass to load from theme-gem if possible

---

.rubocop.yml
jekyll-sass-converter.gemspec

Since Jekyll 3.x is locked to the 1.x series of this plugin, and because Jekyll 4.0 has dropped support for EOL Ruby 2.3

Drop support for Ruby 2.3

---

lib/jekyll/converters/scss.rb
lib/jekyll/source_map_page.rb

Since `page.content` eventually gets rendered into `page.output`, setting the latter manually has no effect if the former is `nil` or empty.

Fix rendering of sourcemap page

---

README.md

Correct the `sass_dir` description and add `load_paths`
Fixes https://github.com/jekyll/jekyll-sass-converter/issues/107

Rectify documentation on sass_dir configuration

---

lib/jekyll/converters/scss.rb

See https://github.com/jekyll/jekyll-sass-converter/pull/131#issuecomment-1049859420

Reduce overall class size

---

Gemfile
lib/jekyll/converters/scss.rb

`sass-embedded` gem recently implemented a [new ruby API](https://www.rubydoc.info/gems/sass-embedded/0.15.0/Sass/Embedded#compile_string-instance_method) that mirrors the behavior of [new sass JS API](https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1450). The old API is deprecated.
This PR updates jekyll-sass-converter to use the new API.

Use new sass-embedded api

---

README.md

`sass-embedded` just had [first stable release 1.0.0](https://rubygems.org/gems/sass-embedded/versions/1.0.0). Removing the note about it being experimental.

Update `sass-embedded` info in `README.md`

---

.github/workflows/ci.yml
.rubocop.yml
Gemfile
README.md
jekyll-sass-converter.gemspec
lib/jekyll/converters/sass.rb
lib/jekyll/converters/scss.rb
script/test
spec/sass_converter_spec.rb
spec/scss_converter_spec.rb
spec/spec_helper.rb

> My proposal would be to produce a new MAJOR version of jekyll-sass-converter that:
> 
> 1. Defaults to the sass-embedded implementation
> 2. Changes this import behavior
> 3. Removes the sassc compatibility entirely
> 4. Documents the upgrade path
Per above comment and discussion in #137, this PR drops support for sassc.
- Remove sassc.
- Bump `required_ruby_version` to `>= 2.6.0` as it is a requirement for `sass-embedded`.
- Drop the undocumented `add_charset` option. Whether to add `@charset` or not will now be automatically determined based on `associate_page_failed?`. If a page is associated, sass will automatically add `@charset` or BOM if output contains any non-ASCII character. Otherwise, e.g. when called via `sassify`/`scssify` filters, `@charset` or BOM will be omitted.
- …

Drop support for sassc

---

README.md
lib/jekyll/converters/scss.rb

This PR adds for two options that refines logging.

Add quiet_deps and verbose option

---

lib/jekyll/converters/scss.rb
spec/sass_converter_spec.rb
spec/scss_converter_spec.rb

This PR removes an extra new line in the css output to make it fully consistent with dart-sass. Previously, a newline is explicitly added to make output compatible with sassc so that the same test case would pass for both implementations. Now the support for sassc is dropped, there is no need to keep that extra newline.
Although this is more of a cosmetic thing, it also has a small performance benefit of avoid copying the frozen string returned from protobuf when source map is disabled.

Remove extra newline in css output

---

README.md

Musl libc is now supported in `sass-embedded 1.58.0`.
This PR updates the requirements for jekyll-sass-converter 3.x in README.md.

Update README with requirements for sass-embedded

---

README.md

This PR is a small documentation update for an outdated link.
Background: https://github.com/sass/dart-sass-embedded got merged into https://github.com/sass/dart-sass in https://github.com/sass/dart-sass/pull/1955.

Update dart-sass repo link in README.md

---

README.md

This PR updates the outdated link for sass embedded protocol in documentation.

Update sass embedded protocol documentation link

---

lib/jekyll/converters/scss.rb

This PR adds a new feature for live-reload where css compilation error will be displayed on the browser. Please see the demo video below on how it works for users.
This feature depends on `sass-embedded >=1.69.6`. In order to simplify the user experience, this PR does not bump up the required dependency version, but rather works based on feature detection. This feature is enabled automatically if sass-embedded supports it.
Demo:
https://github.com/jekyll/jekyll-sass-converter/assets/899645/5903f311-5aad-40a6-9351-76d3cd49a7f9

Display sass error in browser with livereload
